### ISSUE TITLE
Dont know if its possible but, Video Cutscene Before Title screen.

### ISSUE THREAD

**Issue by ByteBrine** [Sonamaker1/What-Psych#2]
### What feature do you want to get added on the **base** engine?

Don't know if its possible but, Video Cutscene Before Title screen...
I'm probably just stupid. sorry for possibly wasting your time. have a good day love the engine!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Sonamaker1** [comment]
Ooo, that's a good idea! I'll see next update if I can fit in a custom menu state right before title screen starts (it will load another hscript file right at the start). Seems simple enough to do.

It would also allow people to skip straight to the main menu, so that's a nice addition 😄  

Thanks, and wish you a great day as well! I will send a message here if this gets added in next update.

**Comment by Sonamaker1** [comment]
Added [InitialState.hx](https://github.com/Sonamaker1/What-Psych/commit/84cb2975ab5f19afe715759257af2cc861d9a8af), which allows you to run hscript on a state before TitleState, (and optionally, skip TitleState entirely).

Closing request!
